<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Elementum_WorkerService-735268a8-3635-437f-ad4c-2990aff3c8d5</UserSecretsId>
    <RootNamespace>Elementum_WorkerService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elementum.Infrastructure\Elementum.Infrastructure.csproj" />
    <ProjectReference Include="..\Elementum.Shared\Elementum.Shared.csproj" />
  </ItemGroup>
</Project>
