// <auto-generated />
using System;
using Elementum.Infrastructure.Outbound.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elementum.Infrastructure.Outbound.Data.Migrations
{
    [DbContext(typeof(ElementumDbContext))]
    [Migration("20260818071741_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Elementum.Domain.Entities.DailyPriceSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ClosePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("close_price");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<decimal?>("ExchangeRateUsdEur")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("exchange_rate_usd_eur");

                    b.Property<decimal>("HighPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("high_price");

                    b.Property<decimal>("LowPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("low_price");

                    b.Property<int>("MetalId")
                        .HasColumnType("int")
                        .HasColumnName("metal_id");

                    b.Property<decimal>("OpenPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("open_price");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("MetalId", "Currency", "EntryDate")
                        .IsUnique();

                    b.ToTable("daily_price_summaries", (string)null);
                });

            modelBuilder.Entity("Elementum.Infrastructure.Outbound.Data.Entities.DistributedLockEntity", b =>
                {
                    b.Property<string>("Resource")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("resource");

                    b.Property<DateTime>("AcquiredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("acquired_at_utc");

                    b.Property<string>("AcquiredBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("acquired_by");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at_utc");

                    b.HasKey("Resource");

                    b.ToTable("distributed_locks", (string)null);
                });

            modelBuilder.Entity("Elementum.Domain.Entities.Metals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("metals", (string)null);
                });

            modelBuilder.Entity("Elementum.Domain.Entities.PriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Ask")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Bid")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Ch")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Chp")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("HighPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("high_price");

                    b.Property<decimal?>("LowPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("low_price");

                    b.Property<int>("MetalId")
                        .HasColumnType("int")
                        .HasColumnName("metal_id");

                    b.Property<decimal?>("OpenPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("open_price");

                    b.Property<string>("OpenTime")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("open_time");

                    b.Property<decimal?>("PrevClosePrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("prev_close_price");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PriceGram10k")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price_gram_10k");

                    b.Property<decimal?>("PriceGram14k")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price_gram_14k");

                    b.Property<decimal?>("PriceGram16k")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price_gram_16k");

                    b.Property<decimal?>("PriceGram18k")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price_gram_18k");

                    b.Property<decimal?>("PriceGram20k")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price_gram_20k");

                    b.Property<decimal?>("PriceGram21k")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price_gram_21k");

                    b.Property<decimal?>("PriceGram22k")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price_gram_22k");

                    b.Property<decimal?>("PriceGram24k")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price_gram_24k");

                    b.Property<string>("ReferenceTimestamp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("reference_timestamp");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MetalId");

                    b.ToTable("price_history", (string)null);
                });

            modelBuilder.Entity("Elementum.Domain.Entities.DailyPriceSummary", b =>
                {
                    b.HasOne("Elementum.Domain.Entities.Metals", "Metal")
                        .WithMany("DailySummaries")
                        .HasForeignKey("MetalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metal");
                });

            modelBuilder.Entity("Elementum.Domain.Entities.PriceHistory", b =>
                {
                    b.HasOne("Elementum.Domain.Entities.Metals", "Metal")
                        .WithMany("PriceHistory")
                        .HasForeignKey("MetalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metal");
                });

            modelBuilder.Entity("Elementum.Domain.Entities.Metals", b =>
                {
                    b.Navigation("DailySummaries");

                    b.Navigation("PriceHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
